---
title: "About Me"
output: 
  html_document:
    toc: false
    toc_float: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I majored in Statistics at Williams College, graduating in 2022 and earning induction into the Mu Sigma Rho and Sigma Xi honor societies for my work within the Statistics major and my undergraduate thesis. After Williams, I moved to Nashville to teach high school mathematics and physics at LEAD Academy High School as part of Teach For America. In addition to teaching, I coached LEAD's cross-country and track teams. Since then, I've transitioned to a career in biostatistics, and I'm ultimately hoping to develop and improve statistical methods that analyze how genetic and/or epigenetic factors impact biological aging and chronic disease.

After earning my MS from Columbia University in May of 2026 with a specialization in statistical genetics, I started my PhD at Vanderbilt that fall. I'm currently working on PhD coursework and am in the process of finding my diessertation topic and advisor. 

My prior coursework has covered topics including probability theory, statistical inference, longitudinal analysis, and modeling using high-dimensional genetic and epigenetic data. Outside of the classroom, I've tested the stability and reliability of new measures of the biological pace of aging, consulted with heart failure clinicians doing cutting-edge research, and used clustering algorithms to improve the effectiveness of computer vision models applied to single-cell imaging. I have experience programming in R, Python, and SQL.

Outside of work, I enjoy long-distance running, jazz piano, chess, cooking, and the outdoors. If you'd like to learn more, feel free to visit my [Outside Work](outside_work.html) page!

Here's a link to my [resume](../Resume/larocca_resume_2026_01.pdf). 
