---
title: "Plot Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(httr)
library(jsonlite)
```

```{r}

get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = 
  get_all_inspections(url) %>%
  bind_rows() 

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

nyc_inspections %>%
  filter(boro == "Manhattan") %>%
  mutate(score = as.numeric(score)) %>%
  plot_ly(
    x = ~score,
    type = "histogram"
  ) %>%
  layout(title = "Histogram of Inspection Scores in Manhattan")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

nyc_inspections %>%
  filter(boro == "Manhattan") %>%
  mutate(score = as.numeric(score)) %>%
  plot_ly(
    x = ~score,
    type = "box"
  ) %>%
  layout(title = "Boxplot of Inspection Scores in Manhattan")

```

### Chart C

```{r}

nyc_inspections %>%
  count(critical_flag) %>%
  plot_ly(
    x = ~critical_flag, y = ~n,
    type = "bar"
  ) %>%
  layout(title = "Bar Graph of Critical Inspection Status")
  
```

#### Note: create a dashboard on the desktop first, because you need a special rendering step to knit it on your website. Use the following code: rmarkdown::render("<FILENAME>.Rmd", output_format = "flexdashboard::flex_dashboard")